import AsyncStorage from '@react-native-async-storage/async-storage';
import React, { createContext, ReactNode, useContext, useEffect, useMemo, useState } from 'react';
import { Platform } from 'react-native';

export type AppLanguage = 'ar' | 'en';

const LANGUAGE_KEY = '@medicare_language';

const translations = {
  ar: {
    home: 'الرئيسية',
    doctors: 'الأطباء',
    appointments: 'المواعيد',
    account: 'حسابي',
    profile: 'الملف الشخصي',
    systemAdmin: 'مسؤول النظام',
    doctorUser: 'طبيب ممارس',
    member: 'عضو',
    doctorDashboard: 'لوحة تحكم الطبيب',
    doctorDashboardSub: 'إدارة المرضى، المواعيد، وجدول العمل',
    adminDashboard: 'لوحة تحكم المسؤول',
    adminDashboardSub: 'إدارة المستخدمين، الأطباء، والتقارير المالية',
    profileCompletion: 'اكتمال الملف الشخصي',
    completeProfileHint: 'أكمل بياناتك المتبقية لتحسين ملفك. المتبقي:',
    profileComplete: 'ملفك الشخصي مكتمل',
    patient: 'مريض',
    consultation: 'استشارة',
    rating: 'تقييم',
    bloodType: 'فصيلة الدم',
    expert: 'خبير',
    weightKg: 'الوزن (كج)',
    accountFinance: 'الحساب والمالية',
    wallet: 'المحفظة وطرق الدفع',
    transactions: 'سجل المعاملات',
    generalSettings: 'الإعدادات العامة',
    editProfile: 'تعديل البيانات',
    languageArabic: 'اللغة (العربية)',
    languageEnglish: 'اللغة (English)',
    notifications: 'التنبيهات',
    privacy: 'الخصوصية والأمان',
    logout: 'تسجيل الخروج',
    chooseLanguage: 'اختر اللغة',
    arabic: 'العربية',
    english: 'English',
    currentLanguage: 'اللغة الحالية',
    chooseAndReload: 'اضغط للتبديل وإعادة تحميل الموقع',
    userFallback: 'مستخدم',
    greetingPrefix: 'مرحباً،',
    homeSubtitle: 'كيف يمكننا مساعدتك اليوم؟',
    results: 'النتائج',
    prescriptions: 'الوصفات',
    healthTipTitle: 'نصيحة اليوم الصحية',
    healthTipDesc: 'شرب 8 أكواب من الماء يومياً يساعد في الحفاظ على نشاط دورتك الدموية.',
    quickActions: 'إجراءات سريعة',
    doctor: 'طبيب',
    chat: 'دردشة',
    emergency: 'طوارئ',
    healthOverview: 'نظرة عامة على صحتك',
    pulseRate: 'معدل النبض',
    bloodPressure: 'ضغط الدم',
    bloodSugar: 'نسبة السكر',
    availableDoctors: 'الأطباء المتاحون',
    searchDoctor: 'ابحث عن طبيب أو تخصص...',
    noDoctors: 'لا يوجد أطباء مطابقين للبحث',
    book: 'حجز',
    myAppointments: 'مواعيدي',
    noAppointments: 'لا توجد مواعيد حالياً. احجز موعد من صفحة الأطباء',
    cancelConfirmTitle: 'تأكيد الإلغاء',
    cancelConfirmMessage: 'هل أنت متأكد من إلغاء هذا الموعد؟',
    yes: 'نعم',
    cancel: 'إلغاء',
    done: 'تم',
    appointmentCancelled: 'تم إلغاء الموعد بنجاح',
    error: 'خطأ',
    appointmentCancelFailed: 'فشل في إلغاء الموعد',
    clinicVisit: 'زيارة عيادة',
    clinicVisitDetails: 'موعدك زيارة عيادة مع',
    dateLabel: 'التاريخ',
    timeLabel: 'الوقت',
    cancelAppointment: 'إلغاء الموعد',
    joinNow: 'انضمام الآن',
    visitDetails: 'تفاصيل الزيارة',
    upcoming: 'قادم',
    completed: 'مكتمل',
    cancelled: 'ملغي',
    videoCall: 'مكالمة فيديو',
    bookAppointment: 'حجز موعد',
    appointmentType: 'نوع الموعد',
    clinicAppointment: 'زيارة العيادة',
    chooseDate: 'اختر التاريخ',
    chooseSuitableDay: 'اختر اليوم المناسب',
    chooseTime: 'اختر الوقت',
    selectDateWarning: 'يرجى اختيار التاريخ',
    selectTimeWarning: 'يرجى اختيار الوقت',
    loginRequired: 'يجب تسجيل الدخول أولاً',
    bookingSuccess: 'تم الحجز',
    bookingFailed: 'فشل في إنشاء الموعد',
    confirmBooking: 'تأكيد الحجز',
    bookingLoading: 'جاري الحجز...',
    welcomeBack: 'أهلاً بك مجدداً',
    loginSubtitle: 'الرجاء تسجيل الدخول للمتابعة',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    forgotPassword: 'نسيت كلمة المرور؟',
    login: 'تسجيل الدخول',
    googleLogin: 'تسجيل الدخول باستخدام جوجل',
    noAccount: 'ليس لديك حساب؟',
    registerNow: 'سجل الآن',
    warning: 'تنبيه',
    enterEmail: 'الرجاء إدخال البريد الإلكتروني',
    enterPassword: 'الرجاء إدخال كلمة المرور',
    invalidLogin: 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
    emailFirst: 'اكتب البريد الإلكتروني أولاً ثم اضغط نسيت كلمة المرور.',
    invalidEmail: 'صيغة البريد الإلكتروني غير صحيحة.',
    resetSentTitle: 'تم إرسال الرابط',
    resetSentMessage: 'تم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك الإلكتروني.\nافتح الإيميل واتبع الخطوات ثم سجل الدخول بكلمة المرور الجديدة.',
    spamHint: 'إذا لم تجد الرسالة في البريد الوارد، راجع الرسائل غير المرغوب فيها (Junk/Spam).',
    createAccount: 'إنشاء حساب جديد',
    registerSubtitle: 'انضم إلى عائلة ميديكير برو اليوم',
    fullName: 'الاسم بالكامل',
    phoneWithCode: 'رقم الهاتف مع كود الدولة',
    doctorRole: 'طبيب',
    patientRole: 'مريض',
    professionData: 'بيانات المهنة',
    specialty: 'التخصص الطبي',
    nationalId: 'رقم الهوية الوطنية',
    medicalCard: 'رقم الكارت الطبي',
    clinicLocation: 'موقع العيادة',
    createAccountEmail: 'إنشاء الحساب وإرسال تأكيد البريد',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
    signIn: 'سجل دخول',
    saveChanges: 'حفظ التغييرات',
    editProfileTitle: 'تعديل الملف الشخصي',
    phone: 'رقم الهاتف',
    bloodTypePlaceholder: 'فصيلة الدم',
    age: 'العمر',
    gender: 'النوع',
    male: 'ذكر',
    female: 'أنثى',
    labResults: 'نتائج التحاليل',
    noResults: 'لا توجد نتائج',
    downloadReport: 'تحميل التقرير (PDF)',
    noNotifications: 'لا توجد تنبيهات',
    noTransactions: 'لا توجد معاملات حالياً',
    paymentMethods: 'طرق الدفع',
    availableBalance: 'الرصيد المتاح',
    topUpBalance: 'شحن الرصيد',
    savedCards: 'البطاقات المسجلة',
    addNewCard: 'إضافة بطاقة جديدة',
    otherOptions: 'خيارات أخرى',
    privacyTitle: 'الخصوصية والأمان',
    accountSecurity: 'أمان الحساب',
    emailVerification: 'تأكيد البريد الإلكتروني',
    phoneVerification: 'تأكيد الهاتف',
    accountStatus: 'حالة الحساب',
    accountRole: 'نوع الحساب',
    createdAt: 'تاريخ إنشاء الحساب',
    verified: 'مؤكد',
    notVerified: 'غير مؤكد',
    active: 'نشط',
    inactive: 'معطل',
    approved: 'معتمد',
    pendingReview: 'قيد المراجعة',
    changePasswordHint: 'لتغيير كلمة المرور استخدم نسيت كلمة المرور من شاشة تسجيل الدخول.',
    goToLogin: 'فتح شاشة تسجيل الدخول',
    manageProfileData: 'إدارة بيانات الملف الشخصي',
    localSessionNote: 'يتم حفظ جلسة الدخول على هذا الجهاز فقط. سجل الخروج من الأجهزة المشتركة بعد الانتهاء.',
    dataPrivacyNote: 'بياناتك الطبية الأساسية تستخدم لعرض ملفك وتحسين تجربة الحجز داخل التطبيق.',
  },
  en: {
    home: 'Home',
    doctors: 'Doctors',
    appointments: 'Appointments',
    account: 'Account',
    profile: 'Profile',
    systemAdmin: 'System admin',
    doctorUser: 'Doctor',
    member: 'Member',
    doctorDashboard: 'Doctor dashboard',
    doctorDashboardSub: 'Manage patients, appointments, and schedule',
    adminDashboard: 'Admin dashboard',
    adminDashboardSub: 'Manage users, doctors, and financial reports',
    profileCompletion: 'Profile completion',
    completeProfileHint: 'Complete your remaining details to improve your profile. Left:',
    profileComplete: 'Your profile is complete',
    patient: 'Patient',
    consultation: 'Consultation',
    rating: 'Rating',
    bloodType: 'Blood type',
    expert: 'Expert',
    weightKg: 'Weight (kg)',
    accountFinance: 'Account and finance',
    wallet: 'Wallet and payment methods',
    transactions: 'Transactions',
    generalSettings: 'General settings',
    editProfile: 'Edit profile',
    languageArabic: 'Language (Arabic)',
    languageEnglish: 'Language (English)',
    notifications: 'Notifications',
    privacy: 'Privacy and security',
    logout: 'Log out',
    chooseLanguage: 'Choose language',
    arabic: 'Arabic',
    english: 'English',
    currentLanguage: 'Current language',
    chooseAndReload: 'Tap to switch and reload the site',
    userFallback: 'User',
    greetingPrefix: 'Hello,',
    homeSubtitle: 'How can we help you today?',
    results: 'Results',
    prescriptions: 'Prescriptions',
    healthTipTitle: "Today's health tip",
    healthTipDesc: 'Drinking 8 glasses of water daily helps keep your blood circulation active.',
    quickActions: 'Quick actions',
    doctor: 'Doctor',
    chat: 'Chat',
    emergency: 'Emergency',
    healthOverview: 'Your health overview',
    pulseRate: 'Pulse rate',
    bloodPressure: 'Blood pressure',
    bloodSugar: 'Blood sugar',
    availableDoctors: 'Available doctors',
    searchDoctor: 'Search for a doctor or specialty...',
    noDoctors: 'No doctors match your search',
    book: 'Book',
    myAppointments: 'My appointments',
    noAppointments: 'No appointments yet. Book from the doctors page',
    cancelConfirmTitle: 'Confirm cancellation',
    cancelConfirmMessage: 'Are you sure you want to cancel this appointment?',
    yes: 'Yes',
    cancel: 'Cancel',
    done: 'Done',
    appointmentCancelled: 'Appointment cancelled successfully',
    error: 'Error',
    appointmentCancelFailed: 'Failed to cancel appointment',
    clinicVisit: 'Clinic visit',
    clinicVisitDetails: 'Your clinic visit is with',
    dateLabel: 'Date',
    timeLabel: 'Time',
    cancelAppointment: 'Cancel appointment',
    joinNow: 'Join now',
    visitDetails: 'Visit details',
    upcoming: 'Upcoming',
    completed: 'Completed',
    cancelled: 'Cancelled',
    videoCall: 'Video call',
    bookAppointment: 'Book appointment',
    appointmentType: 'Appointment type',
    clinicAppointment: 'Clinic visit',
    chooseDate: 'Choose date',
    chooseSuitableDay: 'Choose a suitable day',
    chooseTime: 'Choose time',
    selectDateWarning: 'Please choose a date',
    selectTimeWarning: 'Please choose a time',
    loginRequired: 'You must log in first',
    bookingSuccess: 'Booked',
    bookingFailed: 'Failed to create appointment',
    confirmBooking: 'Confirm booking',
    bookingLoading: 'Booking...',
    welcomeBack: 'Welcome back',
    loginSubtitle: 'Please sign in to continue',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    login: 'Sign in',
    googleLogin: 'Sign in with Google',
    noAccount: "Don't have an account?",
    registerNow: 'Register now',
    warning: 'Warning',
    enterEmail: 'Please enter your email',
    enterPassword: 'Please enter your password',
    invalidLogin: 'Email or password is incorrect',
    emailFirst: 'Enter your email first, then tap forgot password.',
    invalidEmail: 'Invalid email format.',
    resetSentTitle: 'Link sent',
    resetSentMessage: 'A password reset link has been sent to your email.\nOpen it, follow the steps, then sign in with the new password.',
    spamHint: "If you don't find the email in your inbox, check Junk/Spam.",
    createAccount: 'Create a new account',
    registerSubtitle: 'Join the Medicare Pro family today',
    fullName: 'Full name',
    phoneWithCode: 'Phone number with country code',
    doctorRole: 'Doctor',
    patientRole: 'Patient',
    professionData: 'Professional details',
    specialty: 'Medical specialty',
    nationalId: 'National ID',
    medicalCard: 'Medical card number',
    clinicLocation: 'Clinic location',
    createAccountEmail: 'Create account and send verification email',
    alreadyHaveAccount: 'Already have an account?',
    signIn: 'Sign in',
    saveChanges: 'Save changes',
    editProfileTitle: 'Edit profile',
    phone: 'Phone number',
    bloodTypePlaceholder: 'Blood type',
    age: 'Age',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    labResults: 'Lab results',
    noResults: 'No results',
    downloadReport: 'Download report (PDF)',
    noNotifications: 'No notifications',
    noTransactions: 'No transactions yet',
    paymentMethods: 'Payment methods',
    availableBalance: 'Available balance',
    topUpBalance: 'Top up balance',
    savedCards: 'Saved cards',
    addNewCard: 'Add new card',
    otherOptions: 'Other options',
    privacyTitle: 'Privacy and security',
    accountSecurity: 'Account security',
    emailVerification: 'Email verification',
    phoneVerification: 'Phone verification',
    accountStatus: 'Account status',
    accountRole: 'Account type',
    createdAt: 'Account created',
    verified: 'Verified',
    notVerified: 'Not verified',
    active: 'Active',
    inactive: 'Inactive',
    approved: 'Approved',
    pendingReview: 'Pending review',
    changePasswordHint: 'To change your password, use Forgot password from the sign-in screen.',
    goToLogin: 'Open sign-in screen',
    manageProfileData: 'Manage profile data',
    localSessionNote: 'Your session is saved on this device only. Sign out after using shared devices.',
    dataPrivacyNote: 'Your basic medical data is used to show your profile and improve booking inside the app.',
  },
} as const;

type TranslationKey = keyof typeof translations.ar;

interface LanguageContextType {
  language: AppLanguage;
  isRTL: boolean;
  setLanguage: (language: AppLanguage) => Promise<void>;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<AppLanguage>('ar');

  useEffect(() => {
    const loadLanguage = async () => {
      const stored = await AsyncStorage.getItem(LANGUAGE_KEY);
      if (stored === 'ar' || stored === 'en') {
        setLanguageState(stored);
      }
    };
    loadLanguage();
  }, []);

  const value = useMemo<LanguageContextType>(() => {
    const setLanguage = async (nextLanguage: AppLanguage) => {
      await AsyncStorage.setItem(LANGUAGE_KEY, nextLanguage);
      setLanguageState(nextLanguage);
      if (Platform.OS === 'web') {
        window.location.reload();
      }
    };

    return {
      language,
      isRTL: language === 'ar',
      setLanguage,
      t: (key) => translations[language][key] || translations.ar[key],
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
